import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from './components/navigation'; 
  import { IoLogoGithub } from 'react-icons/io5'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marquise - Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
              <Navigation />
              {children}

                  <section id="contact" className="bg-[#101827] text-white">
        <div className="mx-auto flex max-w-6xl flex-col gap-8 px-6 py-4 sm:px-10 md:flex-row md:items-center md:justify-between lg:px-12">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.24em] text-[#c084fc]">
              Let&apos;s Connect
            </p>
          </div> 
          <div className="flex flex-col gap-3 text-[#bac6d3] sm:flex-row">
            <a className="transition hover:text-white" href="mailto:jordan.carter@example.com">
              Email
            </a>
            <a
              className="transition hover:text-white"
              href="https://github.com/mfloyd0"
              target="_blank"
              rel="noreferrer"
            >
                <span style={{ display: 'inline-flex', alignItems: 'center', verticalAlign: 'middle', margin: '0 4px' }}>
                <IoLogoGithub size={20} style={{ marginRight: '6px' }} />
                 @mfloyd0
                </span>
              
            </a>
          </div>
        </div>
      </section>
      </body>
    </html>
  );
}
